# -*- coding: utf-8 -*-
"""
Verified reference list for the revised manuscript.
Springer SPBASIC (author-year) style, alphabetical by first-author surname.
Every entry corresponds to a real, verifiable publication located via
Consensus, Research Gateway (Scholar Gateway), and web search, June 2026.
In-text citations use (Surname Year) keyed by the dict key below.
"""

# key -> (in_text, full_reference)
REFERENCES = {
    "acharya2024star": ("Acharya et al. 2024",
        "Acharya, S., Jain, A., Munkhdalai, T., et al. (2024). Star Attention: efficient LLM inference over long sequences. arXiv preprint arXiv:2411.17116."),
    "ainslie2023gqa": ("Ainslie et al. 2023",
        "Ainslie, J., Lee-Thorp, J., de Jong, M., Zemlyanskiy, Y., Lebron, F., & Sanghai, S. (2023). GQA: training generalized multi-query transformer models from multi-head checkpoints. In Proceedings of the 2023 Conference on Empirical Methods in Natural Language Processing (EMNLP) (pp. 4895-4901)."),
    "alizadeh2024flash": ("Alizadeh et al. 2024",
        "Alizadeh, K., Mirzadeh, S. I., Belenko, D., et al. (2024). LLM in a flash: efficient large language model inference with limited memory. In Proceedings of the 62nd Annual Meeting of the Association for Computational Linguistics (ACL) (pp. 12562-12584)."),
    "an2024leval": ("An et al. 2024",
        "An, C., Gong, S., Zhong, M., et al. (2024). L-Eval: instituting standardized evaluation for long context language models. In Proceedings of the 62nd Annual Meeting of the Association for Computational Linguistics (ACL) (pp. 14388-14411)."),
    "aminabadi2022deepspeed": ("Aminabadi et al. 2022",
        "Aminabadi, R. Y., Rajbhandari, S., Awan, A. A., et al. (2022). DeepSpeed-Inference: enabling efficient inference of transformer models at unprecedented scale. In Proceedings of the International Conference for High Performance Computing, Networking, Storage and Analysis (SC)."),
    "bai2024longbench": ("Bai et al. 2024",
        "Bai, Y., Lv, X., Zhang, J., et al. (2024). LongBench: a bilingual, multitask benchmark for long context understanding. In Proceedings of the 62nd Annual Meeting of the Association for Computational Linguistics (ACL) (pp. 3119-3137)."),
    "bolya2023tome": ("Bolya et al. 2023",
        "Bolya, D., Fu, C.-Y., Dai, X., Zhang, P., Feichtenhofer, C., & Hoffman, J. (2023). Token merging: your ViT but faster. In International Conference on Learning Representations (ICLR)."),
    "brandon2024cla": ("Brandon et al. 2024",
        "Brandon, W., Mishra, M., Nrusimha, A., Panda, R., & Ragan-Kelley, J. (2024). Reducing transformer key-value cache size with cross-layer attention. In Advances in Neural Information Processing Systems (NeurIPS) 37."),
    "chee2023quip": ("Chee et al. 2023",
        "Chee, J., Cai, Y., Kuleshov, V., & De Sa, C. (2023). QuIP: 2-bit quantization of large language models with guarantees. In Advances in Neural Information Processing Systems (NeurIPS) 36."),
    "chen2025pitfalls": ("Chen et al. 2025",
        "Chen, A., et al. (2025). The pitfalls of KV cache compression. arXiv preprint arXiv:2510.00231."),
    "chu2025safekv": ("Chu et al. 2025",
        "Chu, K., et al. (2025). Selective KV-cache sharing to mitigate timing side-channels in LLM inference (SafeKV). arXiv preprint arXiv:2508.08438."),
    "dao2022flashattention": ("Dao et al. 2022",
        "Dao, T., Fu, D. Y., Ermon, S., Rudra, A., & Re, C. (2022). FlashAttention: fast and memory-efficient exact attention with IO-awareness. In Advances in Neural Information Processing Systems (NeurIPS) 35 (pp. 16344-16359)."),
    "dao2023flashattention2": ("Dao 2023",
        "Dao, T. (2023). FlashAttention-2: faster attention with better parallelism and work partitioning. arXiv preprint arXiv:2307.08691 (presented at ICLR 2024)."),
    "daogu2024mamba2": ("Dao and Gu 2024",
        "Dao, T., & Gu, A. (2024). Transformers are SSMs: generalized models and efficient algorithms through structured state space duality. In Proceedings of the 41st International Conference on Machine Learning (ICML)."),
    "deepseek2024mla": ("DeepSeek-AI 2024",
        "DeepSeek-AI. (2024). DeepSeek-V2: a strong, economical, and efficient mixture-of-experts language model. arXiv preprint arXiv:2405.04434."),
    "devlin2019bert": ("Devlin et al. 2019",
        "Devlin, J., Chang, M.-W., Lee, K., & Toutanova, K. (2019). BERT: pre-training of deep bidirectional transformers for language understanding. In Proceedings of NAACL-HLT (pp. 4171-4186)."),
    "dettmers2023spqr": ("Dettmers et al. 2023a",
        "Dettmers, T., Svirschevski, R., Egiazarian, V., et al. (2023). SpQR: a sparse-quantized representation for near-lossless LLM weight compression. In International Conference on Learning Representations (ICLR 2024); arXiv:2306.03078."),
    "dettmers2023qlora": ("Dettmers et al. 2023b",
        "Dettmers, T., Pagnoni, A., Holtzman, A., & Zettlemoyer, L. (2023). QLoRA: efficient finetuning of quantized LLMs. In Advances in Neural Information Processing Systems (NeurIPS) 36."),
    "ding2024longrope": ("Ding et al. 2024",
        "Ding, Y., Zhang, L. L., Zhang, C., et al. (2024). LongRoPE: extending LLM context window beyond 2 million tokens. In Proceedings of the 41st International Conference on Machine Learning (ICML)."),
    "duanmu2024skvq": ("Duanmu et al. 2024",
        "Duanmu, H., Yuan, Z., Li, X., Duan, J., Zhang, X., & Lin, D. (2024). SKVQ: sliding-window key and value cache quantization for large language models. In First Conference on Language Modeling (COLM)."),
    "frantar2023gptq": ("Frantar et al. 2023",
        "Frantar, E., Ashkboos, S., Hoefler, T., & Alistarh, D. (2023). GPTQ: accurate post-training quantization for generative pre-trained transformers. In International Conference on Learning Representations (ICLR)."),
    "frantar2023sparsegpt": ("Frantar and Alistarh 2023",
        "Frantar, E., & Alistarh, D. (2023). SparseGPT: massive language models can be accurately pruned in one-shot. In Proceedings of the 40th International Conference on Machine Learning (ICML) (pp. 10323-10337)."),
    "gao2024cachedattention": ("Gao et al. 2024",
        "Gao, B., He, Z., Sharma, P., et al. (2024). Cost-efficient large language model serving for multi-turn conversations with CachedAttention. In Proceedings of the 2024 USENIX Annual Technical Conference (ATC) (pp. 111-126)."),
    "ge2024fastgen": ("Ge et al. 2024",
        "Ge, S., Zhang, Y., Liu, L., Zhang, M., Han, J., & Gao, J. (2024). Model tells you what to discard: adaptive KV cache compression for LLMs. In International Conference on Learning Representations (ICLR)."),
    "gholami2024memorywall": ("Gholami et al. 2024",
        "Gholami, A., Yao, Z., Kim, S., Hooper, C., Mahoney, M. W., & Keutzer, K. (2024). AI and memory wall. IEEE Micro, 44(3), 33-39."),
    "gu2024mamba": ("Gu and Dao 2024",
        "Gu, A., & Dao, T. (2024). Mamba: linear-time sequence modeling with selective state spaces. In First Conference on Language Modeling (COLM)."),
    "gu2025auditing": ("Gu et al. 2025",
        "Gu, C., Li, X. L., Kuditipudi, R., Liang, P., & Hashimoto, T. (2025). Auditing prompt caching in language model APIs. arXiv preprint arXiv:2502.07776."),
    "han2024lminfinite": ("Han et al. 2024",
        "Han, C., Wang, Q., Peng, H., et al. (2024). LM-Infinite: zero-shot extreme length generalization for large language models. In Proceedings of NAACL-HLT (pp. 3991-4008)."),
    "heo2024neupims": ("Heo et al. 2024",
        "Heo, G., Lee, S., Cho, J., et al. (2024). NeuPIMs: NPU-PIM heterogeneous acceleration for batched LLM inferencing. In Proceedings of the 29th ACM International Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS), Vol. 3 (pp. 722-737)."),
    "holmes2024fastgen": ("Holmes et al. 2024",
        "Holmes, C., Tanaka, M., Wyatt, M., et al. (2024). DeepSpeed-FastGen: high-throughput text generation for LLMs via MII and DeepSpeed-Inference. arXiv preprint arXiv:2401.08671."),
    "hong2024flashdecoding": ("Hong et al. 2024",
        "Hong, K., Dai, G., Xu, J., et al. (2024). FlashDecoding++: faster large language model inference on GPUs. In Proceedings of Machine Learning and Systems (MLSys) 6."),
    "hooper2024kvquant": ("Hooper et al. 2024",
        "Hooper, C., Kim, S., Mohammadzadeh, H., et al. (2024). KVQuant: towards 10 million context length LLM inference with KV cache quantization. In Advances in Neural Information Processing Systems (NeurIPS) 37."),
    "hsieh2024ruler": ("Hsieh et al. 2024",
        "Hsieh, C.-P., Sun, S., Kriman, S., et al. (2024). RULER: what's the real context size of your long-context language models? In First Conference on Language Modeling (COLM)."),
    "jiang2023mistral": ("Jiang et al. 2023a",
        "Jiang, A. Q., Sablayrolles, A., Mensch, A., et al. (2023). Mistral 7B. arXiv preprint arXiv:2310.06825."),
    "jiang2023llmlingua": ("Jiang et al. 2023b",
        "Jiang, H., Wu, Q., Lin, C.-Y., Yang, Y., & Qiu, L. (2023). LLMLingua: compressing prompts for accelerated inference of large language models. In Proceedings of the 2023 Conference on Empirical Methods in Natural Language Processing (EMNLP) (pp. 13358-13376)."),
    "leviathan2023spec": ("Leviathan et al. 2023",
        "Leviathan, Y., Kalman, M., & Matias, Y. (2023). Fast inference from transformers via speculative decoding. In Proceedings of the 40th International Conference on Machine Learning (ICML) (pp. 19274-19286)."),
    "jiang2024mixtral": ("Jiang et al. 2024a",
        "Jiang, A. Q., Sablayrolles, A., Roux, A., et al. (2024). Mixtral of experts. arXiv preprint arXiv:2401.04088."),
    "jiang2024minference": ("Jiang et al. 2024b",
        "Jiang, H., Li, Y., Zhang, C., et al. (2024). MInference 1.0: accelerating pre-filling for long-context LLMs via dynamic sparse attention. In Advances in Neural Information Processing Systems (NeurIPS) 37."),
    "kang2024gear": ("Kang et al. 2024",
        "Kang, H., Zhang, Q., Kundu, S., et al. (2024). GEAR: an efficient KV cache compression recipe for near-lossless generative inference of LLM. arXiv preprint arXiv:2403.05527."),
    "kang2025acon": ("Kang et al. 2025",
        "Kang, M., Lee, J., Kang, J., et al. (2025). ACON: optimizing context compression for long-horizon LLM agents. arXiv preprint arXiv:2510.00615."),
    "kariyappa2026sidequest": ("Kariyappa et al. 2026",
        "Kariyappa, S., Choukse, E., Warrier, S., et al. (2026). SideQuest: model-driven KV cache management for long-horizon agentic reasoning. arXiv preprint arXiv:2602.22603."),
    "kim2024samsung": ("Kim et al. 2024a",
        "Kim, B., Kim, J., Moon, S., et al. (2024). The breakthrough memory solutions for improved performance on LLM inference. IEEE Micro, 44(3), 40-48."),
    "kim2024squeezellm": ("Kim et al. 2024b",
        "Kim, S., Hooper, C., Gholami, A., et al. (2024). SqueezeLLM: dense-and-sparse quantization. In Proceedings of the 41st International Conference on Machine Learning (ICML)."),
    "kim2025kvzip": ("Kim et al. 2025",
        "Kim, J.-H., et al. (2025). KVzip: query-agnostic KV cache compression with context reconstruction. arXiv preprint arXiv:2505.23416."),
    "kwon2023paged": ("Kwon et al. 2023",
        "Kwon, W., Li, Z., Zhuang, S., et al. (2023). Efficient memory management for large language model serving with PagedAttention. In Proceedings of the 29th Symposium on Operating Systems Principles (SOSP) (pp. 611-626)."),
    "lee2024infinigen": ("Lee et al. 2024",
        "Lee, W., Lee, J., Seo, J., & Sim, J. (2024). InfiniGen: efficient generative inference of large language models with dynamic KV cache management. In Proceedings of the 18th USENIX Symposium on Operating Systems Design and Implementation (OSDI) (pp. 155-172)."),
    "li2023alpaserve": ("Li et al. 2023",
        "Li, Z., Zheng, L., Zhong, Y., et al. (2023). AlpaServe: statistical multiplexing with model parallelism for deep learning serving. In Proceedings of the 17th USENIX Symposium on Operating Systems Design and Implementation (OSDI) (pp. 663-679)."),
    "li2024snapkv": ("Li et al. 2024",
        "Li, Y., Huang, Y., Yang, B., et al. (2024). SnapKV: LLM knows what you are looking for before generation. In Advances in Neural Information Processing Systems (NeurIPS) 37."),
    "li2025survey": ("Li et al. 2025",
        "Li, H., Li, Y., Tian, A., et al. (2025). A survey on large language model acceleration based on KV cache management. Transactions on Machine Learning Research (TMLR)."),
    "liang2025accllm": ("Liang et al. 2025",
        "Liang, Y., Wang, H., Shi, M., et al. (2025). AccLLM: accelerating long-context LLM inference via algorithm-hardware co-design. IEEE Transactions on Very Large Scale Integration (VLSI) Systems."),
    "lieber2024jamba": ("Lieber et al. 2024",
        "Lieber, O., Lenz, B., Bata, H., et al. (2024). Jamba: a hybrid transformer-Mamba language model. arXiv preprint arXiv:2403.19887."),
    "lin2024awq": ("Lin et al. 2024",
        "Lin, J., Tang, J., Tang, H., et al. (2024). AWQ: activation-aware weight quantization for on-device LLM compression and acceleration. In Proceedings of Machine Learning and Systems (MLSys) 6."),
    "liu2023scissorhands": ("Liu et al. 2023a",
        "Liu, Z., Desai, A., Liao, F., et al. (2023). Scissorhands: exploiting the persistence of importance hypothesis for LLM KV cache compression at test time. In Advances in Neural Information Processing Systems (NeurIPS) 36."),
    "liu2023dejavu": ("Liu et al. 2023b",
        "Liu, Z., Wang, J., Dao, T., et al. (2023). Deja Vu: contextual sparsity for efficient LLMs at inference time. In Proceedings of the 40th International Conference on Machine Learning (ICML) (pp. 22137-22176)."),
    "liu2024kivi": ("Liu et al. 2024a",
        "Liu, Z., Yuan, J., Jin, H., et al. (2024). KIVI: a tuning-free asymmetric 2bit quantization for KV cache. In Proceedings of the 41st International Conference on Machine Learning (ICML)."),
    "liu2024minicache": ("Liu et al. 2024b",
        "Liu, A., Liu, J., Pan, Z., He, Y., Haffari, G., & Zhuang, B. (2024). MiniCache: KV cache compression in depth dimension for large language models. In Advances in Neural Information Processing Systems (NeurIPS) 37."),
    "liu2024clusterkv": ("Liu et al. 2024c",
        "Liu, G., Li, C., Zhao, J., Zhang, C., & Guo, M. (2024). ClusterKV: manipulating LLM KV cache in semantic space for recallable compression. In Proceedings of the 62nd ACM/IEEE Design Automation Conference (DAC)."),
    "liu2024retrievalattention": ("Liu et al. 2024d",
        "Liu, D., Chen, M., Lu, B., et al. (2024). RetrievalAttention: accelerating long-context LLM inference via vector retrieval. arXiv preprint arXiv:2409.10516."),
    "liu2025chunkkv": ("Liu et al. 2025a",
        "Liu, X., Tang, Z., Dong, P., et al. (2025). ChunkKV: semantic-preserving KV cache compression for efficient long-context LLM inference. arXiv preprint arXiv:2502.00299."),
    "liu2025review": ("Liu et al. 2025b",
        "Liu, Y., Li, X., & Wang, Z. (2025). KV cache compression for inference efficiency in LLMs: a review. In Proceedings of the 4th International Conference on Artificial Intelligence and Intelligent Information Processing (AIIIP)."),
    "luo2025shadow": ("Luo et al. 2025",
        "Luo, Z., et al. (2025). Shadow in the cache: unveiling and mitigating privacy risks of KV-cache in LLM inference. arXiv preprint arXiv:2508.09442."),
    "ma2024bitnet158": ("Ma et al. 2024",
        "Ma, S., Wang, H., Ma, L., et al. (2024). The era of 1-bit LLMs: all large language models are in 1.58 bits. arXiv preprint arXiv:2402.17764."),
    "meng2025transmla": ("Meng et al. 2025",
        "Meng, F., Tang, P., Yao, Z., & Zhang, M. (2025). TransMLA: multi-head latent attention is all you need. arXiv preprint arXiv:2502.07864."),
    "modarressi2025nolima": ("Modarressi et al. 2025",
        "Modarressi, A., Deilamsalehy, H., Dernoncourt, F., et al. (2025). NoLiMa: long-context evaluation beyond literal matching. In Proceedings of the 42nd International Conference on Machine Learning (ICML)."),
    "munkhdalai2024infini": ("Munkhdalai et al. 2024",
        "Munkhdalai, T., Faruqui, M., & Gopal, S. (2024). Leave no context behind: efficient infinite context transformers with Infini-attention. arXiv preprint arXiv:2404.07143."),
    "pang2024partition": ("Pang et al. 2024",
        "Pang, Z., Wang, H., Hu, J., et al. (2024). Cache partitioning for mitigating timing side-channel attacks in LLM serving systems. In 2024 6th International Conference on Frontier Technologies of Information and Computer (ICFTIC)."),
    "peng2023rwkv": ("Peng et al. 2023",
        "Peng, B., Alcaide, E., Anthony, Q., et al. (2023). RWKV: reinventing RNNs for the transformer era. In Findings of the Association for Computational Linguistics: EMNLP 2023 (pp. 14048-14077)."),
    "peng2024yarn": ("Peng et al. 2024",
        "Peng, B., Quesnelle, J., Fan, H., & Shippole, E. (2024). YaRN: efficient context window extension of large language models. In International Conference on Learning Representations (ICLR)."),
    "qin2025cake": ("Qin et al. 2025a",
        "Qin, Z., Cao, Y., Lin, M., et al. (2025). CAKE: cascading and adaptive KV cache eviction with layer preferences. In International Conference on Learning Representations (ICLR)."),
    "qin2025mooncake": ("Qin et al. 2025b",
        "Qin, R., Li, Z., He, W., et al. (2025). Mooncake: a KVCache-centric disaggregated architecture for LLM serving. In Proceedings of the 23rd USENIX Conference on File and Storage Technologies (FAST) (pp. 155-170)."),
    "rehg2024kvcompress": ("Rehg 2024",
        "Rehg, I. (2024). KV-Compress: paged KV-cache compression with variable compression rates per attention head. arXiv preprint arXiv:2410.00161."),
    "ribar2024sparq": ("Ribar et al. 2024",
        "Ribar, L., Chelombiev, I., Hudlass-Galley, L., Blake, C., Luschi, C., & Orr, D. (2024). SparQ attention: bandwidth-efficient LLM inference. In Proceedings of the 41st International Conference on Machine Learning (ICML)."),
    "seo2024ianus": ("Seo et al. 2024",
        "Seo, M., Nam, X. T., Park, J., et al. (2024). IANUS: integrated accelerator based on NPU-PIM unified memory system. In Proceedings of the 29th ACM International Conference on Architectural Support for Programming Languages and Operating Systems (ASPLOS), Vol. 3 (pp. 545-560)."),
    "shazeer2019mqa": ("Shazeer 2019",
        "Shazeer, N. (2019). Fast transformer decoding: one write-head is all you need. arXiv preprint arXiv:1911.02150."),
    "sheng2023flexgen": ("Sheng et al. 2023",
        "Sheng, Y., Zheng, L., Yuan, B., et al. (2023). FlexGen: high-throughput generative inference of large language models with a single GPU. In Proceedings of the 40th International Conference on Machine Learning (ICML) (pp. 31094-31116)."),
    "sheng2024slora": ("Sheng et al. 2024",
        "Sheng, Y., Cao, S., Li, D., et al. (2024). S-LoRA: serving thousands of concurrent LoRA adapters. In Proceedings of Machine Learning and Systems (MLSys) 6."),
    "shi2024keep": ("Shi et al. 2024",
        "Shi, L., Zhang, H., Yao, Y., Li, Z., & Zhao, H. (2024). Keep the cost down: a review on methods to optimize LLM's KV-cache consumption. arXiv preprint arXiv:2407.18003."),
    "song2024earlybird": ("Song et al. 2024",
        "Song, L., Pang, Z., Wang, W., et al. (2024). The early bird catches the leak: unveiling timing side channels in LLM serving systems. IEEE Transactions on Information Forensics and Security."),
    "sun2023retnet": ("Sun et al. 2023",
        "Sun, Y., Dong, L., Huang, S., et al. (2023). Retentive network: a successor to transformer for large language models. arXiv preprint arXiv:2307.08621."),
    "sun2024yoco": ("Sun et al. 2024",
        "Sun, Y., Dong, L., Zhu, Y., et al. (2024). You only cache once: decoder-decoder architectures for language models. In Advances in Neural Information Processing Systems (NeurIPS) 37."),
    "vaswani2017attention": ("Vaswani et al. 2017",
        "Vaswani, A., Shazeer, N., Parmar, N., et al. (2017). Attention is all you need. In Advances in Neural Information Processing Systems (NeurIPS) 30 (pp. 5998-6008)."),
    "wang2023bitnet": ("Wang et al. 2023",
        "Wang, H., Ma, S., Dong, L., et al. (2023). BitNet: scaling 1-bit transformers for large language models. arXiv preprint arXiv:2310.11453."),
    "williams2009roofline": ("Williams et al. 2009",
        "Williams, S., Waterman, A., & Patterson, D. (2009). Roofline: an insightful visual performance model for multicore architectures. Communications of the ACM, 52(4), 65-76."),
    "wolters2024cim": ("Wolters et al. 2024",
        "Wolters, C., Yang, X., Schlichtmann, U., & Suzumura, T. (2024). Memory is all you need: an overview of compute-in-memory architectures for accelerating large language model inference. arXiv preprint arXiv:2406.08413."),
    "wulf1995memorywall": ("Wulf and McKee 1995",
        "Wulf, W. A., & McKee, S. A. (1995). Hitting the memory wall: implications of the obvious. ACM SIGARCH Computer Architecture News, 23(1), 20-24."),
    "wu2024crosslayer": ("Wu and Tu 2024a",
        "Wu, H., & Tu, K. (2024). Layer-condensed KV cache for efficient inference of large language models. In Proceedings of the 62nd Annual Meeting of the Association for Computational Linguistics (ACL) (pp. 11175-11188)."),
    "wu2024systematic": ("Wu and Tu 2024b",
        "Wu, H., & Tu, K. (2024). A systematic study of cross-layer KV sharing for efficient LLM inference. arXiv preprint arXiv:2410.14442."),
    "wu2025promptpeek": ("Wu et al. 2025",
        "Wu, G., Zhang, Z., Zhang, Y., et al. (2025). I know what you asked: prompt leakage via KV-cache sharing in multi-tenant LLM serving. In Proceedings of the 2025 Network and Distributed System Security Symposium (NDSS)."),
    "xiao2024streamingllm": ("Xiao et al. 2024a",
        "Xiao, G., Tian, Y., Chen, B., Han, S., & Lewis, M. (2024). Efficient streaming language models with attention sinks. In International Conference on Learning Representations (ICLR)."),
    "xiao2024infllm": ("Xiao et al. 2024b",
        "Xiao, C., Zhang, P., Han, X., et al. (2024). InfLLM: training-free long-context extrapolation for LLMs with an efficient context memory. In Advances in Neural Information Processing Systems (NeurIPS) 37."),
    "xiao2024duo": ("Xiao et al. 2024c",
        "Xiao, G., Tang, J., Zuo, J., et al. (2024). DuoAttention: efficient long-context LLM inference with retrieval and streaming heads. In International Conference on Learning Representations (ICLR 2025); arXiv:2410.10819."),
    "yuan2025nsa": ("Yuan et al. 2025",
        "Yuan, J., Gao, H., Dai, D., et al. (2025). Native sparse attention: hardware-aligned and natively trainable sparse attention. arXiv preprint arXiv:2502.11089."),
    "yang2020retransformer": ("Yang et al. 2020",
        "Yang, X., Yan, B., Li, H., & Chen, Y. (2020). ReTransformer: ReRAM-based processing-in-memory architecture for transformer acceleration. In Proceedings of the 39th International Conference on Computer-Aided Design (ICCAD)."),
    "yang2024pyramidinfer": ("Yang et al. 2024a",
        "Yang, D., Han, X., Gao, Y., Hu, Y., Zhang, S., & Zhao, H. (2024). PyramidInfer: pyramid KV cache compression for high-throughput LLM inference. In Findings of the Association for Computational Linguistics: ACL 2024 (pp. 3258-3270)."),
    "yang2024doublesparsity": ("Yang et al. 2024b",
        "Yang, S., Sheng, Y., Gonzalez, J. E., Stoica, I., & Zheng, L. (2024). Post-training sparse attention with double sparsity. arXiv preprint arXiv:2408.07092."),
    "yang2025kvlink": ("Yang et al. 2025",
        "Yang, J., Hou, B., Wei, W., Bao, Y., & Chang, S. (2025). KVLink: accelerating large language models via efficient KV cache reuse. arXiv preprint arXiv:2502.16002."),
    "ye2024chunkattention": ("Ye et al. 2024",
        "Ye, L., Tao, Z., Huang, Y., & Li, Y. (2024). ChunkAttention: efficient self-attention with prefix-aware KV cache and two-phase partition. In Proceedings of the 62nd Annual Meeting of the Association for Computational Linguistics (ACL) (pp. 11608-11620)."),
    "ye2025flashinfer": ("Ye et al. 2025",
        "Ye, Z., Chen, L., Lai, R., et al. (2025). FlashInfer: efficient and customizable attention engine for LLM inference serving. In Proceedings of Machine Learning and Systems (MLSys) 7."),
    "yen2025helmet": ("Yen et al. 2025",
        "Yen, H., Gao, T., Hou, M., et al. (2025). HELMET: how to evaluate long-context language models effectively and thoroughly. In International Conference on Learning Representations (ICLR)."),
    "yu2022orca": ("Yu et al. 2022",
        "Yu, G.-I., Jeong, J. S., Kim, G.-W., Kim, S., & Chun, B.-G. (2022). Orca: a distributed serving system for transformer-based generative models. In Proceedings of the 16th USENIX Symposium on Operating Systems Design and Implementation (OSDI) (pp. 521-538)."),
    "yue2024wkvquant": ("Yue et al. 2024",
        "Yue, Y., Yuan, Z., Duanmu, H., Zhou, S., Wu, J., & Nie, L. (2024). WKVQuant: quantizing weight and key/value cache for large language models gains more. arXiv preprint arXiv:2402.12065."),
    "zeng2025subkv": ("Zeng et al. 2025",
        "Zeng, Z., Zhang, T., Lu, Z., et al. (2025). SubKV: quantizing long context KV cache for sub-billion parameter language models on edge devices. Software: Practice and Experience, 55(8), 1287-1304."),
    "zhang2023h2o": ("Zhang et al. 2023",
        "Zhang, Z., Sheng, Y., Zhou, T., et al. (2023). H2O: heavy-hitter oracle for efficient generative inference of large language models. In Advances in Neural Information Processing Systems (NeurIPS) 36."),
    "zhang2024coupled": ("Zhang et al. 2024a",
        "Zhang, T., Yi, J., Xu, Z., & Shrivastava, A. (2024). KV cache is 1 bit per channel: efficient large language model inference with coupled quantization. In Advances in Neural Information Processing Systems (NeurIPS) 37."),
    "zhang2024qhitter": ("Zhang et al. 2024b",
        "Zhang, Z., Liu, S., Chen, R., et al. (2024). Q-Hitter: a better token oracle for efficient LLM inference via sparse-quantized KV cache. In Proceedings of Machine Learning and Systems (MLSys) 6."),
    "zhang2024agentmemory": ("Zhang et al. 2024c",
        "Zhang, Z., Bo, X., Ma, C., et al. (2024). A survey on the memory mechanism of large language model based agents. ACM Transactions on Information Systems."),
    "zhang2025memact": ("Zhang et al. 2025",
        "Zhang, Y., Yang, Z., Liu, J., et al. (2025). Memory-as-action: autonomous context curation for long-horizon agentic tasks. arXiv preprint arXiv:2510.12635."),
    "zhao2024atom": ("Zhao et al. 2024",
        "Zhao, Y., Lin, C.-Y., Zhu, K., et al. (2024). Atom: low-bit quantization for efficient and accurate LLM serving. In Proceedings of Machine Learning and Systems (MLSys) 6."),
    "zheng2024sglang": ("Zheng et al. 2024",
        "Zheng, L., Yin, L., Xie, Z., et al. (2024). SGLang: efficient execution of structured language model programs. In Advances in Neural Information Processing Systems (NeurIPS) 37."),
    "zhou2025mem1": ("Zhou et al. 2025",
        "Zhou, Z., Geng, J., Cai, R., et al. (2025). MEM1: learning to synergize memory and reasoning for efficient long-horizon agents. arXiv preprint arXiv:2506.15841."),
    # ---- expansion (verified additions) ----
    "xiao2023smoothquant": ("Xiao et al. 2023",
        "Xiao, G., Lin, J., Seznec, M., Wu, H., Demouth, J., & Han, S. (2023). SmoothQuant: accurate and efficient post-training quantization for large language models. In Proceedings of the 40th International Conference on Machine Learning (ICML) (pp. 38087-38099)."),
    "ashkboos2024quarot": ("Ashkboos et al. 2024",
        "Ashkboos, S., et al. (2024). QuaRot: outlier-free 4-bit inference in rotated LLMs. In Advances in Neural Information Processing Systems (NeurIPS) 37."),
    "liu2024spinquant": ("Liu et al. 2024",
        "Liu, Z., et al. (2024). SpinQuant: LLM quantization with learned rotations. arXiv preprint arXiv:2405.16406."),
    "lin2024duquant": ("Lin et al. 2024",
        "Lin, H., et al. (2024). DuQuant: distributing outliers via dual transformation makes stronger quantized LLMs. In Advances in Neural Information Processing Systems (NeurIPS) 37."),
    "su2025rotatekv": ("Su et al. 2025",
        "Su, Z., et al. (2025). RotateKV: accurate and robust 2-bit KV cache quantization for LLMs via outlier-aware adaptive rotations. arXiv preprint arXiv:2501.16383."),
    "saxena2024resq": ("Saxena et al. 2024",
        "Saxena, U., et al. (2024). ResQ: mixed-precision quantization of large language models with low-rank residuals. arXiv preprint arXiv:2412.14363."),
    "feng2024adakv": ("Feng et al. 2024",
        "Feng, Y., et al. (2024). Ada-KV: optimizing KV cache eviction by adaptive budget allocation for efficient LLM inference. arXiv preprint arXiv:2407.11550."),
    "cai2024pyramidkv": ("Cai et al. 2024",
        "Cai, Z., et al. (2024). PyramidKV: dynamic KV cache compression based on pyramidal information funneling. arXiv preprint arXiv:2406.02069."),
    "tang2024quest": ("Tang et al. 2024",
        "Tang, J., et al. (2024). Quest: query-aware sparsity for efficient long-context LLM inference. In Proceedings of the 41st International Conference on Machine Learning (ICML)."),
    "dong2024less": ("Dong et al. 2024",
        "Dong, H., et al. (2024). Get more with LESS: synthesizing recurrence with KV cache compression for efficient LLM inference. In Proceedings of the 41st International Conference on Machine Learning (ICML)."),
    "feng2025defensivekv": ("Feng et al. 2025",
        "Feng, Y., et al. (2025). Taming the fragility of KV cache eviction in LLM inference (DefensiveKV). arXiv preprint arXiv:2510.13334."),
    "shen2025lava": ("Shen et al. 2025",
        "Shen, Y., et al. (2025). LAVa: layer-wise KV cache eviction with dynamic budget allocation. arXiv preprint arXiv:2509.09754."),
    "wang2025sagekv": ("Wang et al. 2025",
        "Wang, G., et al. (2025). LLMs know what to drop: self-attention guided KV cache eviction for efficient long-context inference (SAGE-KV). arXiv preprint arXiv:2503.08879."),
    "tu2024vlcache": ("Tu et al. 2024",
        "Tu, D., et al. (2024). VL-Cache: sparsity- and modality-aware KV cache compression for vision-language model inference acceleration. arXiv preprint arXiv:2410.23317."),
    "li2025madakv": ("Li et al. 2025",
        "Li, K., et al. (2025). MadaKV: adaptive modality-perception KV cache eviction for efficient multimodal long-context inference. arXiv preprint arXiv:2506.15724."),
    "huang2025aircache": ("Huang et al. 2025",
        "Huang, K., et al. (2025). AirCache: activating inter-modal relevancy KV cache compression for efficient large vision-language model inference. In Proceedings of the IEEE/CVF International Conference on Computer Vision (ICCV)."),
    "zhong2024distserve": ("Zhong et al. 2024",
        "Zhong, Y., et al. (2024). DistServe: disaggregating prefill and decoding for goodput-optimized large language model serving. In Proceedings of the 18th USENIX Symposium on Operating Systems Design and Implementation (OSDI) (pp. 193-210)."),
    "agrawal2024sarathi": ("Agrawal et al. 2024",
        "Agrawal, A., et al. (2024). Taming throughput-latency tradeoff in LLM inference with Sarathi-Serve. In Proceedings of the 18th USENIX Symposium on Operating Systems Design and Implementation (OSDI) (pp. 117-134)."),
    "hu2024tetriinfer": ("Hu et al. 2024",
        "Hu, C., et al. (2024). Inference without interference: disaggregate LLM inference for mixed downstream workloads (TetriInfer). arXiv preprint arXiv:2401.11181."),
    "wang2025wild": ("Wang et al. 2025b",
        "Wang, J., et al. (2025). KVCache cache in the wild: characterizing and optimizing KVCache cache at a large cloud provider. arXiv preprint arXiv:2506.02634."),
    "yang2025kvshare": ("Yang et al. 2025b",
        "Yang, H., et al. (2025). KVShare: an LLM service system with efficient and effective multi-tenant KV cache reuse. arXiv preprint arXiv:2503.16525."),
    "pan2025kvflow": ("Pan et al. 2025",
        "Pan, Z., et al. (2025). KVFlow: efficient prefix caching for accelerating LLM-based multi-agent workflows. arXiv preprint arXiv:2507.07400."),
    "zheng2024inputsnatch": ("Zheng et al. 2024",
        "Zheng, X., et al. (2024). InputSnatch: stealing input in LLM services via timing side-channel attacks. arXiv preprint arXiv:2411.18191."),
    "shah2024flashattention3": ("Shah et al. 2024",
        "Shah, J., et al. (2024). FlashAttention-3: fast and accurate attention with asynchrony and low-precision. In Advances in Neural Information Processing Systems (NeurIPS) 37."),
    "chen2025attenpim": ("Chen et al. 2025b",
        "Chen, L., et al. (2025). AttenPIM: accelerating LLM attention with dual-mode GEMV in processing-in-memory. In Proceedings of the 62nd ACM/IEEE Design Automation Conference (DAC)."),
    "lee2025paise": ("Lee et al. 2025",
        "Lee, H., et al. (2025). PAISE: PIM-accelerated inference scheduling engine for transformer-based LLM. In 2025 IEEE International Symposium on High-Performance Computer Architecture (HPCA)."),
    "yuan2024lveval": ("Yuan et al. 2024",
        "Yuan, T., et al. (2024). LV-Eval: a balanced long-context benchmark with 5 length levels up to 256K. arXiv preprint arXiv:2402.05136."),
    "li2023loogle": ("Li et al. 2023",
        "Li, J., Wang, M., Zheng, Z., & Zhang, M. (2023). LooGLE: can long-context language models understand long contexts? arXiv preprint arXiv:2311.04939."),
    "zhang2024infinitebench": ("Zhang et al. 2024d",
        "Zhang, X., et al. (2024). Infinity-Bench: extending long context evaluation beyond 100K tokens. In Proceedings of the 62nd Annual Meeting of the Association for Computational Linguistics (ACL) (pp. 15262-15277)."),
    "yan2025memoryr1": ("Yan et al. 2025",
        "Yan, S., et al. (2025). Memory-R1: enhancing large language model agents to manage and utilize memories via reinforcement learning. arXiv preprint arXiv:2508.19828."),
    "hu2025memagentbench": ("Hu et al. 2025",
        "Hu, Y., et al. (2025). Evaluating memory in LLM agents via incremental multi-turn interactions (MemoryAgentBench). arXiv preprint arXiv:2507.05257."),
    "su2024rope": ("Su et al. 2024",
        "Su, J., Ahmed, M., Lu, Y., Pan, S., Wen, B., & Liu, Y. (2024). RoFormer: enhanced transformer with rotary position embedding. Neurocomputing, 568, 127063."),
    "li2025scbench": ("Li et al. 2025c",
        "Li, Y., et al. (2025). SCBench: a KV cache-centric analysis of long-context methods. In International Conference on Learning Representations (ICLR)."),
    "mitchell2019modelcards": ("Mitchell et al. 2019",
        "Mitchell, M., Wu, S., Zaldivar, A., et al. (2019). Model cards for model reporting. In Proceedings of the Conference on Fairness, Accountability, and Transparency (FAccT) (pp. 220-229)."),
    # ---- expansion round 2: missing families ----
    # cross-request KV transport / reuse
    "liu2024cachegen": ("Liu et al. 2024e",
        "Liu, Y., et al. (2024). CacheGen: KV cache compression and streaming for fast large language model serving. In Proceedings of the ACM SIGCOMM 2024 Conference (pp. 38-56)."),
    "yao2024cacheblend": ("Yao et al. 2024",
        "Yao, J., et al. (2024). CacheBlend: fast large language model serving for RAG with cached knowledge fusion. In Proceedings of the Twentieth European Conference on Computer Systems (EuroSys 2025)."),
    "cheng2025lmcache": ("Cheng et al. 2025",
        "Cheng, Y., et al. (2025). LMCache: an efficient KV cache layer for enterprise-scale LLM inference. arXiv preprint arXiv:2508.18203."),
    "hu2024memserve": ("Hu et al. 2024b",
        "Hu, C., et al. (2024). MemServe: context caching for disaggregated LLM serving with elastic memory pool. arXiv preprint arXiv:2406.17565."),
    "xie2025strata": ("Xie et al. 2025",
        "Xie, Z., et al. (2025). Strata: hierarchical context caching for long context language model serving. arXiv preprint arXiv:2508.18572."),
    "ye2025kvcomm": ("Ye et al. 2025b",
        "Ye, H., et al. (2025). KVCOMM: online cross-context KV-cache communication for efficient LLM-based multi-agent systems. arXiv preprint arXiv:2510.05366."),
    "strati2024dejavu": ("Strati et al. 2024",
        "Strati, F., et al. (2024). DejaVu: KV-cache streaming for fast, fault-tolerant generative LLM serving. In Proceedings of the 41st International Conference on Machine Learning (ICML)."),
    # learned / trainable compression
    "zhang2024beacon": ("Zhang et al. 2024e",
        "Zhang, P., et al. (2024). Long context compression with activation beacon. arXiv preprint arXiv:2401.03462."),
    "nawrot2024dmc": ("Nawrot et al. 2024",
        "Nawrot, P., et al. (2024). Dynamic memory compression: retrofitting LLMs for accelerated inference. In Proceedings of the 41st International Conference on Machine Learning (ICML)."),
    "lancucki2025dms": ("Lancucki et al. 2025",
        "Lancucki, A., et al. (2025). Inference-time hyper-scaling with KV cache compression. arXiv preprint arXiv:2506.05345."),
    "chari2025kvdistill": ("Chari et al. 2025",
        "Chari, V., et al. (2025). KV-Distill: nearly lossless learnable context compression for LLMs. arXiv preprint arXiv:2503.10337."),
    "cai2025rkv": ("Cai et al. 2025",
        "Cai, Z., et al. (2025). R-KV: redundancy-aware KV cache compression for training-free reasoning models acceleration. arXiv preprint arXiv:2505.24133."),
    "zhou2024dynamickv": ("Zhou et al. 2024",
        "Zhou, X., et al. (2024). DynamicKV: task-aware adaptive KV cache compression for long context LLMs. arXiv preprint arXiv:2412.14838."),
    "karami2025trellis": ("Karami et al. 2025",
        "Karami, M., et al. (2025). Trellis: learning to compress key-value memory in attention models. arXiv preprint arXiv:2510.07051."),
    # low-rank / SVD cache projection
    "chang2024palu": ("Chang et al. 2024",
        "Chang, C.-C., et al. (2024). Palu: KV-cache compression with low-rank projection. arXiv preprint arXiv:2407.21118."),
    "saxena2024eigen": ("Saxena et al. 2024b",
        "Saxena, U., et al. (2024). Eigen attention: attention in low-rank space for KV cache compression. In Findings of the Association for Computational Linguistics: EMNLP 2024."),
    "yuan2023asvd": ("Yuan et al. 2023",
        "Yuan, Z., et al. (2023). ASVD: activation-aware singular value decomposition for compressing large language models. arXiv preprint arXiv:2312.05821."),
    "zhang2024lorc": ("Zhang et al. 2024f",
        "Zhang, R., et al. (2024). LoRC: low-rank compression for LLMs KV cache with a progressive compression strategy. arXiv preprint arXiv:2410.03111."),
    "lin2024matryoshkakv": ("Lin et al. 2024b",
        "Lin, B., et al. (2024). MatryoshkaKV: adaptive KV compression via trainable orthogonal projection. arXiv preprint arXiv:2410.14731."),
    "zhou2025elitekv": ("Zhou et al. 2025b",
        "Zhou, Y., et al. (2025). EliteKV: scalable KV cache compression via RoPE frequency selection and joint low-rank projection. arXiv preprint arXiv:2503.01586."),
    "ji2025mha2mla": ("Ji et al. 2025",
        "Ji, T., et al. (2025). Towards economical inference: enabling DeepSeek's multi-head latent attention in any transformer-based LLMs (MHA2MLA). arXiv preprint arXiv:2502.14837."),
    "yu2024kvheads": ("Yu et al. 2024",
        "Yu, H., et al. (2024). Effectively compress KV heads for LLM. arXiv preprint arXiv:2406.07056."),
    # eviction follow-ons
    "adnan2024keyformer": ("Adnan et al. 2024",
        "Adnan, M., et al. (2024). Keyformer: KV cache reduction through key tokens selection for efficient generative inference. In Proceedings of Machine Learning and Systems (MLSys) 6."),
    "tang2024razorattention": ("Tang et al. 2024b",
        "Tang, H., et al. (2024). RazorAttention: efficient KV cache compression through retrieval heads. In International Conference on Learning Representations (ICLR 2025); arXiv:2407.15891."),
    "guo2024vatp": ("Guo et al. 2024",
        "Guo, Z., et al. (2024). Attention score is not all you need for token importance indicator in KV cache reduction: value also matters. In Proceedings of the 2024 Conference on Empirical Methods in Natural Language Processing (EMNLP)."),
    "chen2024nacl": ("Chen et al. 2024b",
        "Chen, Y., et al. (2024). NACL: a general and effective KV cache eviction framework for LLM at inference time. In Proceedings of the 62nd Annual Meeting of the Association for Computational Linguistics (ACL)."),
    "behnam2025rocketkv": ("Behnam et al. 2025",
        "Behnam, P., et al. (2025). RocketKV: accelerating long-context LLM inference via two-stage KV cache compression. arXiv preprint arXiv:2502.14051."),
    "park2025keydiff": ("Park et al. 2025",
        "Park, J., et al. (2025). KeyDiff: key similarity-based KV cache eviction for long-context LLM inference in resource-constrained environments. arXiv preprint arXiv:2504.15364."),
    "goel2025caote": ("Goel et al. 2025",
        "Goel, R., et al. (2025). CAOTE: KV cache selection for LLMs via attention output error-based token eviction. arXiv preprint arXiv:2504.14051."),
    # mixed-precision adaptive + structural finding
    "lei2026arkv": ("Lei et al. 2026",
        "Lei, J., et al. (2026). ARKV: adaptive and resource-efficient KV cache management under limited memory budget for long-context inference in LLMs. arXiv preprint arXiv:2603.08727."),
    "salfati2026quantrank": ("Salfati 2026",
        "Salfati, S. (2026). Quantization dominates rank reduction for KV-cache compression. arXiv preprint arXiv:2604.11501."),
    # speculative decoding family
    "cai2024medusa": ("Cai et al. 2024b",
        "Cai, T., et al. (2024). Medusa: simple LLM inference acceleration framework with multiple decoding heads. In Proceedings of the 41st International Conference on Machine Learning (ICML)."),
    "li2024eagle": ("Li et al. 2024b",
        "Li, Y., et al. (2024). EAGLE: speculative sampling requires rethinking feature uncertainty. In Proceedings of the 41st International Conference on Machine Learning (ICML)."),
    # multimodal (extend §4.5)
    "li2025scalekv": ("Li et al. 2025d",
        "Li, K., et al. (2025). Memory-efficient visual autoregressive modeling with scale-aware KV cache compression (ScaleKV). arXiv preprint arXiv:2505.19602."),
    # ---- recent work (H1 2026), substantiating the June-2026 cut-off ----
    "an2026restkv": ("An et al. 2026",
        "An, Y., et al. (2026). ReST-KV: robust KV cache eviction with layer-wise output reconstruction and spatial-temporal smoothing. OpenReview (forum PhEHuo7oMm)."),
    "yang2026capkv": ("Yang et al. 2026",
        "Yang, J., et al. (2026). Rethinking KV cache eviction via a unified information-theoretic objective (CapKV). arXiv preprint arXiv:2604.25975."),
    "ahn2026lookaheadkv": ("Ahn et al. 2026",
        "Ahn, J., et al. (2026). LookaheadKV: fast and accurate KV cache eviction by glimpsing into the future without generation. In International Conference on Learning Representations (ICLR 2026); arXiv:2603.10899."),
    "wang2026crystalkv": ("Wang et al. 2026",
        "Wang, Z., et al. (2026). Crystal-KV: efficient KV cache management for chain-of-thought LLMs via answer-first principle. arXiv preprint arXiv:2601.16986."),
    "chen2026kvcore": ("Chen et al. 2026",
        "Chen, J., et al. (2026). KV-CoRE: benchmarking data-dependent low-rank compressibility of KV-caches in LLMs. arXiv preprint arXiv:2602.05929."),
    "yao2026factoredkeys": ("Yao et al. 2026",
        "Yao, H., et al. (2026). Thin keys, full values: reducing KV cache via low-dimensional attention selection. arXiv preprint arXiv:2603.04427."),
    "benfenati2026stief": ("Benfenati et al. 2026",
        "Benfenati, L., et al. (2026). Don't be so Stief! Learning KV cache low-rank approximation over the Stiefel manifold. arXiv preprint arXiv:2601.21686."),
    "ma2026orbitflow": ("Ma et al. 2026",
        "Ma, X., et al. (2026). OrbitFlow: SLO-aware long-context LLM serving with fine-grained KV cache reconfiguration. arXiv preprint arXiv:2601.10729."),
    "he2026ampd": ("He et al. 2026",
        "He, W., et al. (2026). Efficient multi-round LLM inference over disaggregated serving (AMPD). arXiv preprint arXiv:2602.14516."),
    "basit2026dualscale": ("Basit et al. 2026",
        "Basit, O., Liu, Y., Kong, Z. J., & Hu, Y. C. (2026). BiScale: energy-efficient disaggregated LLM serving via phase-aware placement and DVFS. arXiv preprint arXiv:2602.18755."),
    "wang2026optileak": ("Wang et al. 2026b",
        "Wang, L., et al. (2026). OptiLeak: efficient prompt reconstruction via reinforcement learning in multi-tenant LLM services. arXiv preprint arXiv:2602.20595."),
    "yamamoto2026bitflip": ("Yamamoto et al. 2026",
        "Yamamoto, Y., et al. (2026). Bit-flip vulnerability of shared KV-cache blocks in LLM serving systems. arXiv preprint."),
    "wang2026latencydos": ("Wang et al. 2026c",
        "Wang, T., et al. (2026). Rethinking latency denial-of-service: attacking the LLM serving framework, not the model. arXiv preprint arXiv:2602.07878."),
    "zhang2026actmem": ("Zhang et al. 2026",
        "Zhang, X., et al. (2026). ActMem: bridging the gap between memory retrieval and reasoning in LLM agents. arXiv preprint arXiv:2603.00026."),
    "ye2026memweaver": ("Ye et al. 2026",
        "Ye, J., et al. (2026). MemWeaver: weaving hybrid memories for traceable long-horizon agentic reasoning. arXiv preprint arXiv:2601.18204."),
    "zhao2026amabench": ("Zhao et al. 2026",
        "Zhao, Y., et al. (2026). AMA-Bench: evaluating long-horizon memory for agentic applications. arXiv preprint arXiv:2602.22769."),
    "zhang2026hermes": ("Zhang et al. 2026b",
        "Zhang, H., et al. (2026). HERMES: KV cache as hierarchical memory for efficient streaming video understanding. arXiv preprint arXiv:2601.14724."),
    # ---- competing surveys (for differentiation, Table 1 / Section 1.4) ----
    "xu2026kvstrategies": ("Xu et al. 2026",
        "Xu, Y., Khaira, N. K., & Singh, T. (2026). KV cache optimization strategies for scalable and efficient LLM inference. arXiv preprint arXiv:2603.20397."),
    "jiang2026systemaware": ("Jiang et al. 2026",
        "Jiang, J., Yang, P., Zhang, R., et al. (2026). Towards efficient large language model serving: a survey on system-aware KV cache optimization. In Findings of the Association for Computational Linguistics: ACL 2026."),
    "zhen2025taming": ("Zhen et al. 2025",
        "Zhen, R., Li, J., Ji, Y., et al. (2025). Taming the titans: a survey of efficient LLM inference serving. arXiv preprint arXiv:2504.19720."),
    # ---- broader efficiency surveys (reviewer-expected context) ----
    "yuan2024roofline": ("Yuan et al. 2024",
        "Yuan, Z., Shang, Y., Zhou, Y., et al. (2024). LLM inference unveiled: survey and roofline model insights. arXiv preprint arXiv:2402.16363."),
    "zhou2024effsurvey": ("Zhou et al. 2024",
        "Zhou, Z., Ning, X., Hong, K., et al. (2024). A survey on efficient inference for large language models. arXiv preprint arXiv:2404.14294."),
    "wan2024effllm": ("Wan et al. 2024",
        "Wan, Z., Wang, X., Liu, C., et al. (2024). Efficient large language models: a survey. Transactions on Machine Learning Research (TMLR)."),
    "miao2023serving": ("Miao et al. 2023",
        "Miao, X., Oliaro, G., Zhang, Z., et al. (2023). Towards efficient generative large language model serving: a survey from algorithms to systems. arXiv preprint arXiv:2312.15234."),
    "liu2025longcontext": ("Liu et al. 2025c",
        "Liu, J., Zhu, D., Bai, Z., et al. (2025). A comprehensive survey on long context language modeling. arXiv preprint arXiv:2503.17407."),
    "sun2025effattn": ("Sun et al. 2025",
        "Sun, Y., Dong, L., Zhu, Y., et al. (2025). Efficient attention mechanisms for large language models: a survey. arXiv preprint arXiv:2507.19595."),
    "li2024hwperspective": ("Li et al. 2024c",
        "Li, J., Xu, J., Huang, S., et al. (2024). Large language model inference acceleration: a comprehensive hardware perspective. arXiv preprint arXiv:2410.04466."),
    # ---- canonical methods a reviewer would expect ----
    "oren2024tova": ("Oren et al. 2024",
        "Oren, M., Hassid, M., Yarden, N., Adi, Y., & Schwartz, R. (2024). Transformers are multi-state RNNs (TOVA). In Proceedings of the 2024 Conference on Empirical Methods in Natural Language Processing (EMNLP)."),
    "singhania2024loki": ("Singhania et al. 2024",
        "Singhania, P., Singh, S., He, S., Feizi, S., & Bhatele, A. (2024). Loki: low-rank keys for efficient sparse attention. In Advances in Neural Information Processing Systems (NeurIPS) 37."),
    "hooper2024squeezed": ("Hooper et al. 2024",
        "Hooper, C., Kim, S., Mohammadzadeh, H., et al. (2024). Squeezed attention: accelerating long context length LLM inference. arXiv preprint arXiv:2411.09688."),
    "yang2024tidaldecode": ("Yang et al. 2024c",
        "Yang, L., Zhang, Z., Chen, Z., Li, Z., & Jia, Z. (2024). TidalDecode: fast and accurate LLM decoding with position persistent sparse attention. arXiv preprint arXiv:2410.05076."),
}


import re
from collections import defaultdict


def _surname(full):
    head = re.match(r"^(.*?)\(\d{4}", full).group(1)
    first = head.split(",")[0].strip()
    return first.rstrip(".")


def _year(full):
    return re.search(r"\((\d{4})", full).group(1)


def _strip_suffix(label):
    return re.sub(r"(\b\d{4})[a-z]\b", r"\1", label)


# Compute year-letter suffixes automatically so that in-text labels and the
# reference-list entries are always mutually consistent and follow Springer
# author-year (SPBASIC) rules: entries sharing a first-author surname and year
# receive a, b, c... in the order they appear in the alphabetised reference list.
def _build_disambiguation():
    groups = defaultdict(list)  # (surname, year) -> [keys]
    for k, (lab, full) in REFERENCES.items():
        groups[(_surname(full), _year(full))].append(k)
    suffix = {}
    for (sn, yr), keys in groups.items():
        if len(keys) == 1:
            suffix[keys[0]] = ""
        else:
            ordered = sorted(keys, key=lambda kk: REFERENCES[kk][1].lower())
            for i, kk in enumerate(ordered):
                suffix[kk] = chr(ord("a") + i)
    return suffix


_SUFFIX = _build_disambiguation()


def intext(key):
    lab = _strip_suffix(REFERENCES[key][0])
    s = _SUFFIX[key]
    if s:
        lab = re.sub(r"(\b\d{4})\b", r"\1" + s, lab)
    return lab


def _ref_with_suffix(key):
    full = REFERENCES[key][1]
    s = _SUFFIX[key]
    if s:
        full = re.sub(r"\((\d{4})\)", r"(\1" + s + ")", full, count=1)
    return full


def _collapse_authors(ref):
    """Integrity safeguard: for any entry whose author block was truncated with
    'et al.', keep ONLY the verified first author plus 'et al.', so that no
    reconstructed (and possibly inaccurate) co-author names are asserted.
    Entries with a fully enumerated author list (no 'et al.') are left intact."""
    if ", et al." not in ref:
        return ref
    head, rest = ref.split(" (", 1)            # head = author block
    parts = head.split(", ")
    first = parts[0] + ", " + parts[1] if len(parts) >= 2 else parts[0]
    return f"{first}, et al. ({rest}"


def sorted_reference_strings():
    return sorted((_collapse_authors(_ref_with_suffix(k)) for k in REFERENCES),
                  key=lambda s: s.lower())
